### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#17]
Basis tests are missing on these features:
- [ ] Add tests on BCI2000 axes. 
- [ ] Add tests on topocentric axes.
- [ ] Add tests on surface points.
- [ ] Add tests on geodesy routines.

Other minor tests are also needed across the entire package

**Comment by andreapasquale94** [comment]
Outdated, will reopen another one following #54.
