### ISSUE TITLE
Add legacy inertial frames

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#19]
Add the following legacy inertial frames that are built-in in SPICE N067:

- [ ] B1950
- [ ] FK4
- [ ] GALACTIC
- [ ] ECLIPB1950

See SPICE _chgirf.f_ for details on these axes definitions.

**Comment by MicheleCeresoli** [comment]
What do you think @andreapasquale94?

**Comment by andreapasquale94** [comment]
These frames have been inserted and tested, closing.

**Comment by MicheleCeresoli** [comment]
More detailed and accurate implementations of the FK4/FK5/Galactic frames are needed. 
See Lieske (1976, 1979) and Standish (1989) and Murray (1989).

**Comment by andreapasquale94** [comment]
@MicheleCeresoli I believe we can close this. Those frames could be implemented by the users independently if needed.
