### ISSUE TITLE
Provide high-level function to load all the point/axes in ephemeris files

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#22]
Provide a high-level interface function to allow the user to automatically load (when possible) all the points and axes that are stored within the loaded ephemeris provider, similarly to GODOT's [addEphem](https://godot.io.esa.int/godotpy/api_reference/generated/godot.model.frames.Frames.html#godot.model.frames.Frames.addEphem).

**Comment by andreapasquale94** [comment]
Done with #54 .
