### ISSUE TITLE
Loss of accuracy of some tests 

### ISSUE THREAD

**Issue by andreapasquale94** [JuliaSpaceMissionDesign/FrameTransformations.jl#26]
The last update reveals a loss of accuracy in some transformations. 
I had to change the following test tolerance to `1e-4` from `1e-6`.

https://github.com/JuliaSpaceMissionDesign/FrameTransformations.jl/blob/8a6f46a93864eee79fbd2d6e0f8fc3620409ed30/test/Orient/moon.jl#L60

https://github.com/JuliaSpaceMissionDesign/FrameTransformations.jl/blob/8a6f46a93864eee79fbd2d6e0f8fc3620409ed30/test/Orient/moon.jl#L67

The reason should be investigated.
Maybe due to the change from Calceph to `Ephemerides` in the tests?

**Comment by MicheleCeresoli** [comment]
Some tests are also failing in the axes and points testsets when using `Ephemerides.jl` instead of Calceph, however this happens sporadically.

**Comment by andreapasquale94** [comment]
Outdated.
