### ISSUE TITLE
Standardise IERS routines API and conventions 

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#40]
Increase the consistency between the different conventions and function names. The following conventions should be implemented: 
- [ ] IERS [1996](https://www.iers.org/IERS/EN/Publications/TechnicalNotes/tn21.html-1.htm?nn=94912)
- [ ] IERS [2003](https://www.iers.org/IERS/EN/Publications/TechnicalNotes/tn32.html)
- [ ] IERS [2010](https://www.iers.org/IERS/EN/Publications/TechnicalNotes/tn36.html-1.htm?nn=94912)

For each convention, the following quantities should be computable:
- Earth Rotation Angle
- Frame Bias
- Mean obliquity of the ecliptic
- Precession angles (for both 3-angles and 4-angles rotations)
- Precession matrix
- Nutation in longitude and obliquity
- Nutation matrix
- Greenwich Mean Sidereal Time (GMST) 
- Greenwich Apparent Sidereal Time (GAST)
- ITRF to GCRF rotation matrix

**Comment by andreapasquale94** [comment]
Moved to [IERSConventions.jl](https://github.com/JuliaSpaceMissionDesign/IERSConventions.jl).
