### ISSUE TITLE
Rework IERS series parser

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#43]
As part of the general IERS framework rework of #40, it is desirable to increase the flexibility and capabilities of the `build_series` function that is currently responsible of generating efficient functions for the evaluation of the nutation series. 

The parser should have the following capabilities: 
- Parse series for both nutation components and CIO X, Y and s + XY/s coordinates.
- Parse text files: this should avoid the need to translate the original IERS tables into Julia files, avoiding potential transcription errors. 
- Simultaneous computation of multiple quantities: this saves-up time because it avoids the repeated computation of the sine and cosine of series with the same fundamental arguments.
- Support coefficients with different orders of magnitude: the output should always be in radians but the input coefficients should be translatable to arcseconds via multiplicative factors.

**Comment by andreapasquale94** [comment]
Moved to [IERSConventions.jl](https://github.com/JuliaSpaceMissionDesign/IERSConventions.jl).
