### ISSUE TITLE
Make directions return unit-vectors

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#66]
All direction functions should return unit-vectors as agreed in #65:

- [ ] The existing functions should implement normalisation. 
- [ ] ```add_direction_normalize``` should be removed. 
- [ ] The users should be informed that their custom-made direction functions should return unit-vectors.

**Comment by andreapasquale94** [comment]
Done in v3.0.
