### ISSUE TITLE
Error when using add_point_dynamical due to incorrect SVectorNT vector size

### ISSUE THREAD

**Issue by jackyarndley** [JuliaSpaceMissionDesign/FrameTransformations.jl#69]
When using a point defined with the function `add_point_dynamical!` there is an error due to the incorrect sizing of the SVectorNT.

For example, in the case of an order 4 frame system, the vector is assumed to be size 12, but the functions only return vectors of size 3, 6, 9 and 12 (the size 12 works fine). I am not sure if the size of the requested vector can be changed and there is a better way to do this, but I made a draft commit zero-padding these vectors to the correct size which fixes the issue.

https://github.com/jackyarndley/FrameTransformations.jl/commit/85cc5d5f0ef53c7da6e35b6e80d97a70e13a4cc3

**Comment by jackyarndley** [comment]
Hi, @andreapasquale94 I don't have the exact error on hand, but I can try to explain. On line 177 of points.jl we have: 

```t -> SVectorNT{3O, N}(fun(t)),```

The SVectorNT expects a size of `3O`, which in this case is 12 (with a frame system order of 4), whereas we only initialize the vector with a size of 3 (fun(t) returns only the position). An error occurs because we try to create a SVectorNT of size 12 with only a size 3 vector.

**Comment by andreapasquale94** [comment]
Sorry but this is not the case, as I said, `SVectorNT` is a temporary alias of `SVector` that has some additional constructors here: https://github.com/JuliaSpaceMissionDesign/FrameTransformations.jl/blob/7d89177b9277316b953f14f0f020eb481bca7554/src/Core/nodes.jl#L14

As a MWE:

```julia
g = FrameSystem{4, Float64}()
add_axes_root!(g, :Root, 1)
add_point_root!(g, :Root, 0, 1)

f(t) = SA[t, t, t]
add_point_dynamical!(g, :Point, 1, 0, 1, f)

vector3(g, 0, 1, 1, 10.0)
vector6(g, 0, 1, 1, 10.0)
vector9(g, 0, 1, 1, 10.0)
vector12(g, 0, 1, 1, 10.0)
```

**Comment by andreapasquale94** [comment]
I probably found the problem: did you tried to enter the API functions with an integer for the time argument?

**Comment by jackyarndley** [comment]
Thank you very much for the MWE. I didn't notice the additional constructors! 

 I've run the MWE on my machine and no error occurs, but on further testing it seems that if the functions provided to `add_point_dynamical!` are vectors (not SA vectors) the error occurs as the constructors don't cover this case. I'm unsure if this is intended or not.
 
I'm definitely looking forward to checking out `v3.0`

```
g = FrameSystem{4, Float64}()
add_axes_root!(g, :Root, 1)
add_point_root!(g, :Root, 0, 1)

f(t) = [t, t, t]
add_point_dynamical!(g, :Point, 1, 0, 1, f)

vector3(g, 0, 1, 1, 10.0)
vector6(g, 0, 1, 1, 10.0)
vector9(g, 0, 1, 1, 10.0)
vector12(g, 0, 1, 1, 10.0)
