### ISSUE TITLE
can't open  tutorials in stable documentation. Is there anyone like me?. plz update.

### ISSUE THREAD

**Issue by Narutoyw** [JuliaSpaceMissionDesign/FrameTransformations.jl#72]
![p1](https://github.com/user-attachments/assets/fa823ab8-5ae1-4237-8b81-7128365e92c1)

**Comment by MicheleCeresoli** [comment]
Hello @Narutoyw, you are right, I experience the same issue because it seems the associated HTML were not generated. We will fix this as soon as possible, thanks for reporting it!

**Comment by Narutoyw** [comment]
> Hello @Narutoyw, you are right, I experience the same issue because it seems the associated HTML were not generated. We will fix this as soon as possible, thanks for reporting it!

thx very very much!

**Comment by andreapasquale94** [comment]
Fixed, for now the `dev` docs only is fixed, on the next patch I will also fix the `stable` docs.
