### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MicheleCeresoli** [JuliaSpaceMissionDesign/FrameTransformations.jl#9]
- [x] Remove Utils from the roadmap.
- [ ] Add documentation for loading EOP data.
- [ ] Add light-time transformation tutorial
- [ ] Add tutorial for IERS routines
- [x] Separate use case examples from tutorials
- [ ] Fix HiFi Earth-Moon example with the new EOP interface
- [ ] Fix some documentation typos
- [ ] Add multi-threading tutorial
- [ ] Add Autodiff tutorial

**Comment by andreapasquale94** [comment]
Outdated, will open a new one following #54.
